Minor refactoring

diff --git a/scripts/package b/scripts/package
--- a/scripts/package
+++ b/scripts/package
@@ -30,23 +30,25 @@ uv lock --upgrade
 
 cd "$BASE_DIR/src/$PACKAGE"
 echo "--- Apply formatting ---"
-uvx ruff check --fix
-uvx ruff format
-
-echo "--- Perform static type checking for modules ---"
 cd "$BASE_DIR/packages/$PACKAGE"
-uv add mypy pyright --dev # Make sure type checkers are installed as development dependencies
+uv add ruff --dev # Make sure formatter is installed as development dependencies
 # shellcheck source=/dev/null
 source .venv/bin/activate
 # Workaround for virtual environment not activating correctly in some cases
 PYTHON=$(pwd)/.venv/bin/python
+$PYTHON --version
+$PYTHON -m ruff check --fix
+$PYTHON -m ruff format
+
+echo "--- Perform static type checking for modules ---"
+uv add mypy pyright --dev # Make sure type checkers are installed as development dependencies
 cd "$BASE_DIR/src"
-echo -n "mypy " && $PYTHON -m mypy --package $PACKAGE --package ms_common \
+echo -n "mypy " && $PYTHON -m mypy --package "$PACKAGE" --package ms_common \
     --strict \
     --follow-untyped-imports \
     --platform linux \
     --python-version 3.12
-echo -n "pyright " && PYRIGHT_PYTHON_FORCE_VERSION=latest $PYTHON -m pyright --project $PACKAGE || : # "Ignore" Pyright errors
+echo -n "pyright " && PYRIGHT_PYTHON_FORCE_VERSION=latest $PYTHON -m pyright --project "$PACKAGE" || : # "Ignore" Pyright errors
 
 check-coverage-and-annotations() {
     echo "... Check docstring coverage ..."
